[default]
    data_file_path='neural/data/reactome_pathways_API.xlsx'
    prompt_template_file_path='neural/templates/task_prompts.json'
    sttm_template_file_path='neural/templates/statements.json'
    scheme_template_file_path='neural/templates/schemes.json'